sequence = input("Введите последовательность ДНК: ")
sequence_upper = sequence.upper()
count_A = sequence_upper.count('A')
count_T = sequence_upper.count('T')
count_G = sequence_upper.count('G')
count_C = sequence_upper.count('C')
total_length = len(sequence)
print("\n=== Анализ последовательности ДНК ===\n")
print(f"Введите последовательность ДНК: {sequence}")
print(f"\nПоследовательность в верхнем регистре: {sequence_upper}")
print("\nПодсчёт нуклеотидов:")
print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}")
print(f"\nОбщая длина: {total_length} нуклеотидов")
if total_length > 0:
    print("\nПроцентное содержание:")
    print(f"A: {(count_A / total_length * 100):.1f}%")
    print(f"T: {(count_T / total_length * 100):.1f}%")
    print(f"G: {(count_G / total_length * 100):.1f}%")
    print(f"C: {(count_C / total_length * 100):.1f}%")